name: page-deploy

on:
  push:
    branches:
    - main

jobs:
  first-pass:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: Install dependencies
      run: cd Shutdown/jmdjr.github.io && npm install
    # - name: Run tests
    #   run: cd Shutdown/jmdjr.github.io && npm run test:headless
    - name: Build
      run: cd Shutdown/jmdjr.github.io && npm run build
    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist/
        enable_jekyll: true
  second-pass:
    runs-on: ubuntu-latest
    needs: first-pass
    permissions: 
      id-token: write
      pages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        submodules: recursive
        repository: jmdjr/jmdjr.github.io
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: build
      uses: actions/jekyll-build-pages@v1.0.13
      with: 
        source: dist/
        destination: ./_site
    - name: package
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./_site
        name: github-pages
    - name: deploy
      uses: actions/deploy-pages@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        artifact_name: github-pages
        preview: false