name: page-deploy

on:
  push:
    branches:
    - main

jobs:
  sync:
    name: 'submodule-sync'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
        token: ${{ secrets.GITHUB_TOKEN }}
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Update references
    - name: Git Submodule Update
      run: |
        git pull --recurse-submodules
        git submodule update --remote --recursive

    - name: Commit update
      run: |
        git config --global user.name 'Git bot'
        git config --global user.email 'bot@noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git commit -am "Auto updated submodule references" && git push || echo "No changes to commit"
        
  build-and-commit:
    runs-on: ubuntu-latest
    needs: sync
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install
    # - name: Run tests
    #   run: cd Shutdown/jmdjr.github.io && npm run test:headless
    - name: Build
      run: npm run build
    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ../../dist/browser
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-commit
    permissions: 
      id-token: write
      pages: write
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: gh-pages
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Build
      uses: actions/jekyll-build-pages@v1
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
    - name: deploy
      uses: actions/deploy-pages@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        artifact_name: github-pages
        preview: false
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}