name: page-deploy

on:
  push:
    branches:
    - main

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: Install dependencies
      run: npm install
    # - name: Run tests
    #   run: cd Shutdown/jmdjr.github.io && npm run test:headless
    - name: Build
      run: npm run build
    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ../../dist/browser
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-commit
    permissions: 
      id-token: write
      pages: write
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: gh-pages
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Build
      uses: actions/jekyll-build-pages@v1
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
    - name: deploy
      uses: actions/deploy-pages@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        artifact_name: github-pages
        preview: false
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}